# This workflow will do a clean install of node dependencies, build the source code for every push and pull requests

name: Lint & Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  LintBuild:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Use Node.js 20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
      - name: ğŸ“¦ Install Dependencies
        run: npm install
      - name: ğŸ¨ Eslint
        run: npm run lint
      - name: ğŸ“¦ Build
        run: npm run build
